import { Priority, Role, TicketStatus } from '../../generated/prisma/client.js';
import { prisma } from '../../lib/prisma.js';
import { getAiProvider } from './provider.js';

type ClassificationResult = {
  category: string;
  priority: Priority;
  autoResolvable: boolean;
  autoReply: string | null;
};

const allowedCategories = new Set(['Billing', 'Technical', 'Account', 'General', 'Other']);
const allowedPriorities = new Set(Object.values(Priority));

export async function summarizeTicket(subject: string, description: string) {
  const prompt = `SUMMARIZE_TICKET
Write a concise 1-2 sentence support-ticket summary for an agent queue.

Subject: ${subject}
Description: ${description}`;

  return getAiProvider().generateText(prompt, {
    temperature: 0.2,
  });
}

export async function classifyTicket(
  subject: string,
  description: string,
): Promise<ClassificationResult> {
  const prompt = `CLASSIFY_TICKET
Classify this customer support ticket.

Return only valid JSON with this shape:
{
  "category": "Billing" | "Technical" | "Account" | "General" | "Other",
  "priority": "LOW" | "MEDIUM" | "HIGH" | "URGENT",
  "autoResolvable": boolean,
  "autoReply": string | null
}

Only set autoResolvable true for simple, low-risk requests like password reset instructions or business hours. Do not auto-resolve billing disputes, security issues, outages, refunds, account deletion, or anything ambiguous.

Subject: ${subject}
Description: ${description}`;

  const text = await getAiProvider().generateText(prompt, {
    temperature: 0.1,
    responseMimeType: 'application/json',
  });
  const parsed = parseJsonObject(text);
  const category = typeof parsed.category === 'string' ? parsed.category : 'Other';
  const priority = typeof parsed.priority === 'string' ? parsed.priority : Priority.MEDIUM;
  const autoReply = typeof parsed.autoReply === 'string' ? parsed.autoReply.trim() : null;

  return {
    category: allowedCategories.has(category) ? category : 'Other',
    priority: allowedPriorities.has(priority as Priority)
      ? (priority as Priority)
      : Priority.MEDIUM,
    autoResolvable: parsed.autoResolvable === true && Boolean(autoReply),
    autoReply,
  };
}

export async function polishReply(draft: string) {
  const prompt = `POLISH_REPLY
Rewrite this support-agent reply to be clearer, warmer, and more professional.
Keep the meaning the same. Do not add promises, discounts, policies, or facts that are not present.

Draft:
${draft}`;

  return getAiProvider().generateText(prompt, {
    temperature: 0.3,
  });
}

export async function enrichTicketWithAi(ticketId: string, subject: string, description: string) {
  try {
    const [summary, classification] = await Promise.all([
      summarizeTicket(subject, description),
      classifyTicket(subject, description),
    ]);
    const aiUser =
      classification.autoResolvable && classification.autoReply
        ? await ensureAiAssistantUser()
        : null;

    await prisma.$transaction(async (tx) => {
      await tx.ticket.update({
        where: {
          id: ticketId,
        },
        data: {
          aiSummary: summary,
          category: classification.category,
          aiSuggestedPriority: classification.priority,
          status: aiUser ? TicketStatus.AUTO_RESOLVED : undefined,
          resolvedAt: aiUser ? new Date() : undefined,
        },
      });

      if (aiUser && classification.autoReply) {
        await tx.reply.create({
          data: {
            ticketId,
            authorId: aiUser.id,
            body: `${classification.autoReply}\n\nThis response was generated by AI. Reply here if you still need help.`,
          },
        });
        await tx.auditEvent.create({
          data: {
            ticketId,
            actorId: aiUser.id,
            action: 'ticket.auto_resolved',
            fromValue: TicketStatus.OPEN,
            toValue: TicketStatus.AUTO_RESOLVED,
          },
        });
      }
    });

    return loadTicketWithRelations(ticketId);
  } catch (error) {
    console.warn('AI enrichment skipped:', error instanceof Error ? error.message : error);
    return null;
  }
}

async function ensureAiAssistantUser() {
  const email = 'ai-assistant@aiticketing.local';
  const existing = await prisma.user.findUnique({
    where: {
      email,
    },
  });

  if (existing) {
    return existing;
  }

  return prisma.user.create({
    data: {
      email,
      name: 'AI Support Assistant',
      passwordHash: 'system-user-no-login',
      role: Role.AGENT,
      isActive: false,
    },
  });
}

async function loadTicketWithRelations(ticketId: string) {
  return prisma.ticket.findUnique({
    where: {
      id: ticketId,
    },
    include: {
      customer: true,
      agent: true,
      replies: {
        where: {
          isInternal: false,
        },
        orderBy: {
          createdAt: 'asc',
        },
        include: {
          author: true,
        },
      },
      auditEvents: {
        orderBy: {
          createdAt: 'asc',
        },
      },
    },
  });
}

function parseJsonObject(text: string) {
  const trimmed = text.trim();
  const jsonText = trimmed.startsWith('{')
    ? trimmed
    : (trimmed.match(/```json\s*([\s\S]*?)```/)?.[1] ?? trimmed.match(/\{[\s\S]*\}/)?.[0]);

  if (!jsonText) {
    return {};
  }

  try {
    return JSON.parse(jsonText) as Record<string, unknown>;
  } catch {
    return {};
  }
}
