// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { config } from 'dotenv';
import { defineConfig } from 'prisma/config';

config({ path: resolve(dirname(fileURLToPath(import.meta.url)), '.env') });

const { DATABASE_URL, POSTGRES_URL, POSTGRES_PRISMA_URL, PRIVATE_DATABASE_URL, RAILWAY_DATABASE_URL } = process.env;
const resolvedUrl = DATABASE_URL || POSTGRES_URL || POSTGRES_PRISMA_URL || PRIVATE_DATABASE_URL || RAILWAY_DATABASE_URL;

if (resolvedUrl) {
  process.env.DATABASE_URL = resolvedUrl;
}

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
    seed: 'tsx prisma/seed.ts',
  },
  datasource: {
    url: process.env['DATABASE_URL'],
  },
});
